# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5731038d64227e4f9feb1244f36dbe0e33f6cf11f857c471ef264443259033466bb393af172a392eb8b73d657d734b4b7c5e050cd3fca28f1fa42fbccd5e10e9

test:
  secret_key_base: 8d86469283b24e653a39266d9f802faec6f432bbc74e347a05a4094ce3d175b5d9df0405c0ee63dde4bf98268e38f3c903979cc117deda1448f3d5b03eb01f7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
